### PR TITLE
Update drift comparison view url-rules

### PR DESCRIPTION
**Pull request by johnsonm325**
Previously we were tracking any non-parameter string that followed `/drift/`. This was wrapping in any visit to `/drift/` as well as `/drift/baselines/*`.

This PR fixes that so we can track views on `/drift/` that include parameters. So now we can track when people are viewing a comparison.

### CODE REVIEW

**Comment by johnsonm325** [comment]
I have been made aware that this does not give us what we need. Changing this to [WIP].

**Comment by johnsonm325** [comment]
This is ready for review now. Removing [WIP].

**Comment by johnsonm325** [comment]
@ryelo I haven't seen the Travis CI - Branch run start at all since I opened this PR up. Is there something I need to do to get it to work?

**Comment by ryelo** [comment]
@johnsonm325 it was incorrectly using branch instead of pull request, it should be fine now

**Review by allieh782 — APPROVED** [review]

**Pull request merged**
