### PR TITLE
Add Image Builder

### PR DESCRIPTION
**Pull request by andreasn**
Only wizard for now, as that's our first thing to measure.

### CODE REVIEW

**Comment by andreasn** [comment]
This is my first attempt at this, so not 100% certain about the syntax.
@mmenestr please take a look!

**Comment by andreasn** [comment]
Service is only for beta still. https://console.redhat.com/beta/insights/image-builder/imagewizard

**Comment by mmenestr** [comment]
Looks good to me - only thing is you need to add the actual "scope" string to say which app and bundle it should be tracking these in. Having the {} in the features don't actually do anything unless you have a scope defined above.

@ryelo  can you help with that part, it should be bundle = insights, and app = image-builder - right @andreasn ?

**Comment by andreasn** [comment]
> @ryelo can you help with that part, it should be bundle = insights, and app = image-builder - right @andreasn ?

Yes, sounds correct!

**Comment by andreasn** [comment]
@mmenestr OK! Added the bundle and app info now. Looks better?

**Comment by mmenestr** [comment]
I believe so, nice job haha now just have to wait for @ryelo to approve!

**Comment by ryelo** [comment]
Sorry, encountered some weird build errors. Redid the tests, so once they pass I will merge!

**Pull request merged**
